# Use the official Node.js image
FROM node:20-alpine3.20 AS base

# Install system deps for swc/esbuild/node-gyp
RUN apk add --no-cache libc6-compat python3 make g++ bash

# Set working directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm@9

# Copy only package.json and lockfile
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Build the client admin app
FROM base AS client-xpoll-admin-dev-build

# Run the build script
RUN pnpm run build:development

# Final production image with Nginx
FROM nginx:alpine AS client-react-xpoll-admin-dev

# Copy built files
COPY --from=client-xpoll-admin-dev-build /app/dist /usr/share/nginx/html

# Copy nginx config
COPY --from=client-xpoll-admin-dev-build /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
