export const CAMPAIGN_PLANS = {
  NP_1M_PLAN: "NP_1M_PLAN",
  NP_1M_PLUS_PLAN: "NP_1M_PLUS_PLAN",
  NP_3M_PLAN: "NP_3M_PLAN",
  NP_3M_PLUS_PLAN: "NP_3M_PLUS_PLAN",
  NP_6M_PLAN: "NP_6M_PLAN",
  NP_6M_PLUS_PLAN: "NP_6M_PLUS_PLAN",
  P_1M_PLAN: "P_1M_PLAN",
  P_1M_PLUS_PLAN: "P_1M_PLUS_PLAN",
  P_3M_PLAN: "P_3M_PLAN",
  P_3M_PLUS_PLAN: "P_3M_PLUS_PLAN",
  P_6M_PLAN: "P_6M_PLAN",
  P_6M_PLUS_PLAN: "P_6M_PLUS_PLAN",
};

export const plusPlans = [
  CAMPAIGN_PLANS.NP_1M_PLUS_PLAN,
  CAMPAIGN_PLANS.NP_3M_PLUS_PLAN,
  CAMPAIGN_PLANS.NP_6M_PLUS_PLAN,
  CAMPAIGN_PLANS.P_1M_PLUS_PLAN,
  CAMPAIGN_PLANS.P_3M_PLUS_PLAN,
  CAMPAIGN_PLANS.P_6M_PLUS_PLAN,
];
